<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\transport\models\base;

use Yii;

/**
 * This is the base-model class for table "tr_student_stop_points".
 *
 * @property integer $id
 * @property string $student_id
 * @property string $stop_name
 * @property string $route_name
 * @property string $vehicle_no
 * @property string $driver_id
 * @property integer $driver_phone
 *
 * @property \app\modules\transport\models\TrVehicleDetails $vehicleNo
 * @property \app\modules\transport\models\Students $student
 * @property \app\modules\transport\models\TrStopDetails $stopName
 * @property \app\modules\transport\models\TrRouteDetails $routeName
 */
abstract class TrStudentStopPoints extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tr_student_stop_points';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_id', 'stop_name', 'route_name', 'vehicle_no', 'driver_id', 'driver_phone'], 'required'],
            [['driver_phone'], 'integer'],
            [['student_id', 'stop_name', 'route_name', 'vehicle_no', 'driver_id'], 'string', 'max' => 120]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'student_id' => 'Student ID',
            'stop_name' => 'Stop Name',
            'route_name' => 'Route Name',
            'vehicle_no' => 'Vehicle No',
            'driver_id' => 'Driver ID',
            'driver_phone' => 'Driver Phone',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVehicleNo()
    {
        return $this->hasOne(\app\modules\transport\models\TrVehicleDetails::className(), ['vehicle_no' => 'vehicle_no']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(\app\modules\students\models\Students::className(), ['student_id' => 'student_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStopName()
    {
        return $this->hasOne(\app\modules\transport\models\TrStopDetails::className(), ['stop_name' => 'stop_name']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRouteName()
    {
        return $this->hasOne(\app\modules\transport\models\TrRouteDetails::className(), ['route_name' => 'route_name']);
    }




}
