<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\modules\transport\models\TrStudentStopPoints $model
* @var yii\widgets\ActiveForm $form
*/

$this->registerJsFile('advanced/frontend/web/plugins/select2/select2.min.js', ['depends'=> [\yii\web\JqueryAsset::className()]]);
$this->registerJs('$("#trstudentstoppoints-student_id").select2()');
?>
<link href="plugins/select2/select2.min.css" rel="stylesheet">
<div class="tr-student-stop-points-form">

    <?php $form = ActiveForm::begin([
    'id' => 'TrStudentStopPoints',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'id')->textInput() ?>
			<?php  // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
			$students = \app\modules\students\models\Students::find()->all();
			foreach ($students as $student){
				$stus[$student->student_id] = $student->name.
				' ('.$student->	class. ') '.' ['.$student->student_id.']';
			}	
			
			echo $form->field($model, 'student_id')->dropDownList($stus, ['prompt' => 'Select']
); ?>
