<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\modules\transport\models\TrStudentStopPoints $model
* @var yii\widgets\ActiveForm $form
*/

$this->registerJsFile('advanced/frontend/web/plugins/select2/select2.min.js', ['depends'=> [\yii\web\JqueryAsset::className()]]);
$this->registerJs('$("#trstudentstoppoints-student_id").select2()');
?>
<link href="plugins/select2/select2.min.css" rel="stylesheet">
<div class="tr-student-stop-points-form">

    <?php $form = ActiveForm::begin([
    'id' => 'TrStudentStopPoints',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            
			<?= $form->field($model, 'id')->textInput() ?>
			<?php  // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
			$students = \app\modules\students\models\Students::find()->all();
			foreach ($students as $student){
				$stus[$student->student_id] = $student->name.
				' ('.$student->	class. ') '.' ['.$student->student_id.']';
			}	
			
			echo $form->field($model, 'student_id')->dropDownList($stus, ['prompt' => 'Select']
); ?>
<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'route_name')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\modules\transport\models\TrRouteDetails::find()->all(), 'route_name', 'route_name'),
    ['prompt' => 'Select']
); ?>

			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'stop_name')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\modules\transport\models\TrStopDetails::find()->all(), 'stop_name', 'stop_name'),
    ['prompt' => 'Select']
); ?>

			
			<?= // generated by schmunk42\giiant\generators\crud\providers\RelationProvider::activeField
$form->field($model, 'vehicle_no')->dropDownList(
    \yii\helpers\ArrayHelper::map(app\modules\transport\models\TrVehicleDetails::find()->all(), 'vehicle_no', 'vehicle_no'),
    ['prompt' => 'Select']
); ?>
			<?= $form->field($model, 'driver_id')->textInput(['maxlength' => true]) ?>
			<?= $form->field($model, 'driver_phone')->textInput() ?>
        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                   'encodeLabels' => false,
                     'items' => [ [
    'label'   => 'TrStudentStopPoints',
    'content' => $this->blocks['main'],
    'active'  => true,
], ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? 'Create' : 'Save'),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>
<script>
$(document).ready(function(){
	$("#trstudentstoppoints-route_name").change(function(){
		$.ajax({
			url:'<?php echo Yii::$app->urlManager->createUrl('transport/tr-student-stop-points/create');?>',
			
			success: function(data){
			console.log(data);
				var a = $("#trstudentstoppoints-route_name").parent().parent();
			$(data).insertAfter(a);
			},
		});
	});
});
</script>
