<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
    * @var app\modules\transport\models\TrStudentStopPointsSearch $searchModel
*/

$this->title = 'Tr Student Stop Points';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="giiant-crud tr-student-stop-points-index">

    <?php //             echo $this->render('_search', ['model' =>$searchModel]);
        ?>

    
    <?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

    <h1>
        <?= 'Tr Student Stop Points' ?>        <small>
            List
        </small>
    </h1>
    <div class="clearfix crud-navigation">
        <div class="pull-left">
            <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']) ?>
        </div>

        <div class="pull-right">

                                                                                                                                        
            <?= 
            \yii\bootstrap\ButtonDropdown::widget(
            [
            'id' => 'giiant-relations',
            'encodeLabel' => false,
            'label' => '<span class="glyphicon glyphicon-paperclip"></span> ' . 'Relations',
            'dropdown' => [
            'options' => [
            'class' => 'dropdown-menu-right'
            ],
            'encodeLabels' => false,
            'items' => [            [
                'url' => ['tr-vehicle-details/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Tr Vehicle Details' . '</i>',
            ],            [
                'url' => ['students/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Students' . '</i>',
            ],            [
                'url' => ['tr-stop-details/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Tr Stop Details' . '</i>',
            ],            [
                'url' => ['tr-route-details/index'],
                'label' => '<i class="glyphicon glyphicon-arrow-right">&nbsp;' . 'Tr Route Details' . '</i>',
            ],]
            ],
            'options' => [
            'class' => 'btn-default'
            ]
            ]
            );
            ?>        </div>
    </div>


    <div class="table-responsive">
        <?= GridView::widget([
        'layout' => '{summary}{pager}{items}{pager}',
        'dataProvider' => $dataProvider,
        'pager' => [
        'class' => yii\widgets\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel' => 'Last'        ],
                    'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
        'headerRowOptions' => ['class'=>'x'],
        'columns' => [

                [
            'class' => 'yii\grid\ActionColumn',
            'urlCreator' => function($action, $model, $key, $index) {
                // using the column name as key, not mapping to 'id' like the standard generator
                $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                $params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
                return Url::toRoute($params);
            },
            'contentOptions' => ['nowrap'=>'nowrap']
        ],
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'student_id',
    'value' => function ($model) {
        if ($rel = $model->getStudent()->one()) {
            return Html::a($rel->name, ['students/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'stop_name',
    'value' => function ($model) {
        if ($rel = $model->getStopName()->one()) {
            return Html::a($rel->id, ['tr-stop-details/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'route_name',
    'value' => function ($model) {
        if ($rel = $model->getRouteName()->one()) {
            return Html::a($rel->id, ['tr-route-details/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
			// generated by schmunk42\giiant\generators\crud\providers\RelationProvider::columnFormat
[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'vehicle_no',
    'value' => function ($model) {
        if ($rel = $model->getVehicleNo()->one()) {
            return Html::a($rel->id, ['tr-vehicle-details/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
			'driver_id',
			'driver_phone',
        ],
        ]); ?>
    </div>

</div>


<?php \yii\widgets\Pjax::end() ?>



